### ISSUE TITLE
Undefined behavior from `undefined` comparisons

### ISSUE THREAD

**Issue by lann** [patterns/pink-elephants#45]
Hello,

I work on Fermyon Cloud. We noticed an issue with your app leading to high CPU usage and shut down your app to mitigate the problem.

I believe the specific issue in this case was this line: https://github.com/patterns/pink-elephants/blob/d0c141390938337337075f59ab8626c4451ddb62/src/verify/verifier.zig#L49

According to https://github.com/ziglang/zig/issues/15527#issuecomment-1529184481:
> comparing against a value that is undefined is illegal and considered [Undefined Behavior](https://ziglang.org/documentation/master/#Undefined-Behavior).

In this particular case it appears that the undefined behavior ended up compiling into an infinite loop.

**Comment by patterns** [comment]
Sorry, I'll fix that conditional. Thanks for tracking down the issue. I knew I did something wrong. This is helpful, very appreciated!

**Comment by patterns** [comment]
The steps I made:
- remove the conditional, and replace with initialization of the variable with a default.
- specify ReleaseSafe instead of ReleaseSmall `zig build -Dtarget=wasm32-wasi -Doptimize=ReleaseSafe`
For a couple weeks, monitored this build binary version running in raspi and the average CPU is below 0.4. So now with Spin 2.0 almost live, I'm curious how this performs and pushed a deploy to Fermyon Cloud this time and it is live so far!

**Comment by patterns** [comment]
merged with the issue #49 which is concerned with filtering delete activity, but we were testing several changes mashed together.
